#!/data/data/com.termux/files/usr/bin/dash
API_STR="-D__ANDROID_API__="
API_LEVEL="$(getprop ro.build.version.sdk)"
CONFIG_FILE="<config file path>"
echo "Updating Clang's config file..."
# We now can just append __ANDROID_API__ to the file.
echo "${API_STR}${API_LEVEL}" >> "${CONFIG_FILE}"
